@startuml

package 読込 {
    class 読込
}

package 統計 {
    class 統計
    読込 <. 統計
    統計 ..> 最大値
    統計 ..> 最小値
    統計 ..> 平均値
    統計 ..> 標準偏差
}

package 可視化 {
    class 可視化
    統計 <. 可視化
    可視化 ..> グラフ
    グラフ ..> データの種類
    グラフ ..> グラフの種類
    グラフ ..> グラフの色
    グラフ ..> マーカーの種類
    グラフ ..> アスペクト比
}

package ユーザー {
    class ユーザー
    読込 ..> ユーザー
}

package CSVファイル {
    class CSVファイル
    読込 ..> CSVファイル
}

@enduml