@startuml

package ファイル読込 {
    class ファイル読込
}

package 統計 {
    class 統計
    ファイル読込 <. 統計
}

package 可視化 {
    class 可視化
    統計 <. 可視化
}

package ユーザー {
    class ユーザー
    ファイル読込 ..> ユーザー
}

package CSVファイル {
    class CSVファイル
    ファイル読込 ..> CSVファイル
}

@enduml