@startuml

ユーザー --> 解析ツール : 読み込ませるCSVファイルのパスを指定する
解析ツール --> 解析ツール : 指定されたファイルが読込可能か確認する
解析ツール --> 解析ツール : 読み込んでデータフレームを作成する
解析ツール --> 解析ツール : 各データの統計量を計算する
ユーザー <-- 解析ツール : 読み込んだデータ一覧と統計量を表示
ユーザー --> 解析ツール : 可視化したいデータを一覧から選択する
ユーザー --> 解析ツール : 作成したいグラフの各種設定を決める
ユーザー --> 解析ツール : グラフ作成を指示する
ユーザー <-- 解析ツール : グラフを表示する

@enduml